export const categories = [
    { id: "all", nameTr: "Tüm Kategoriler", nameEn: "All Categories" },
    { id: "kraft", nameTr: "Kraft Kaseler", nameEn: "Kraft Bowls" },
    { id: "white", nameTr: "Beyaz Kaseler", nameEn: "White Bowls" }
  ];
  
export const initialProducts = [
    {
      id: "prod-550-white",
      titleTr: "550 CC Salata Kabı (Beyaz)",
      titleEn: "550 CC Salad Bowl (White)",
      descTr: "550 cc Salata Kabı, %99 geri dönüştürülebilir yapısıyla çevre dostu ve hijyenik bir ambalaj çözümü sunar.",
      descEn: "550 cc Salad Bowl offers an eco-friendly and hygienic packaging solution with 99% recyclable structure.",
      category: "white",
      volume: "550 CC",
      imgMain: "./images/prods/550_white_main.webp",
      imgSub: "./images/prods/550_white_sub.webp",
      specs: {
        topDiameter: "150 mm",
        bottomDiameter: "128 mm",
        height: "45 mm",
        boxQty: "300 Adet / pcs",
        dimensions: "46*31*45 cm"
      }
    },
    {
      id: "prod-550-kraft",
      titleTr: "550 CC Kraft Salata Kabı",
      titleEn: "550 CC Kraft Salad Bowl",
      descTr: "550 cc Kraft Salata Kabı, doğal kraft dokusuyla üst düzey sunum sağlayan, dayanıklı ve doğa dostu bir seçimdir.",
      descEn: "550 cc Kraft Salad Bowl providing premium presentation with natural kraft texture. High quality and eco-friendly.",
      category: "kraft",
      volume: "550 CC",
      imgMain: "./images/prods/550_kraft_main.webp",
      imgSub: "./images/prods/550_kraft_sub.webp",
      specs: {
        topDiameter: "150 mm",
        bottomDiameter: "128 mm",
        height: "45 mm",
        boxQty: "300 Adet / pcs",
        dimensions: "46*31*45 cm"
      }
    },
    {
      id: "prod-750-white",
      titleTr: "750 CC Salata Kabı (Beyaz)",
      titleEn: "750 CC Salad Bowl (White)",
      descTr: "750 cc Salata Kabı, orta boy porsiyonlar için idealdir. Gıda sertifikalı kartondan üretilmiş olup sıvıya dayanıklıdır.",
      descEn: "750 cc Salad Bowl ideal for medium portions. Made of food-certified paperboard, resists liquids.",
      category: "white",
      volume: "750 CC",
      imgMain: "./images/prods/750_white_main.webp",
      imgSub: "./images/prods/750_white_sub.webp",
      specs: {
        topDiameter: "150 mm",
        bottomDiameter: "128 mm",
        height: "60 mm",
        boxQty: "300 Adet / pcs",
        dimensions: "46*31*55 cm"
      }
    },
    {
      id: "prod-750-kraft",
      titleTr: "750 CC Kraft Salata Kabı",
      titleEn: "750 CC Kraft Salad Bowl",
      descTr: "750 cc Doğal Kraft Salata Kabı. Ekolojik duyarlılığa sahip işletmeler için özel olarak tasarlanmıştır. Şık ve sızdırmaz.",
      descEn: "750 cc Natural Kraft Salad Bowl. Specially designed for eco-conscious businesses. Elegant and leak-proof.",
      category: "kraft",
      volume: "750 CC",
      imgMain: "./images/prods/750_kraft_main.webp",
      imgSub: "./images/prods/750_kraft_sub.webp",
      specs: {
        topDiameter: "150 mm",
        bottomDiameter: "128 mm",
        height: "60 mm",
        boxQty: "300 Adet / pcs",
        dimensions: "46*31*55 cm"
      }
    },
    {
      id: "prod-32oz-white",
      titleTr: "32 OZ Salata Kabı (Beyaz)",
      titleEn: "32 OZ Salad Bowl (White)",
      descTr: "32 OZ Salata Kabı, büyük porsiyon salatalar ve sıcak yemekler için mükemmel beyaz estetik tasarım.",
      descEn: "32 OZ Salad Bowl, perfect white aesthetic design for large portion salads and hot meals.",
      category: "white",
      volume: "32 OZ",
      imgMain: "./images/prods/32oz_white_main.webp",
      imgSub: "./images/prods/32oz_white_sub.webp",
      specs: {
        topDiameter: "185 mm",
        bottomDiameter: "160 mm",
        height: "53 mm",
        boxQty: "300 Adet / pcs",
        dimensions: "57*38*56 cm"
      }
    },
    {
      id: "prod-32oz-kraft",
      titleTr: "32 OZ Kraft Salata Kabı",
      titleEn: "32 OZ Kraft Salad Bowl",
      descTr: "32 OZ Doğal Kraft Salata Kabı, yüksek gramajlı gıda kartonu sayesinde ekstra dayanıklılık sağlar.",
      descEn: "32 OZ Natural Kraft Salad Bowl provides extra durability thanks to its high-grammage food paperboard.",
      category: "kraft",
      volume: "32 OZ",
      imgMain: "./images/prods/32oz_kraft_main.webp",
      imgSub: "./images/prods/32oz_kraft_sub.webp",
      specs: {
        topDiameter: "185 mm",
        bottomDiameter: "160 mm",
        height: "53 mm",
        boxQty: "300 Adet / pcs",
        dimensions: "57*38*56 cm"
      }
    },
    {
      id: "prod-38oz-white",
      titleTr: "38 OZ Salata Kabı (Beyaz)",
      titleEn: "38 OZ Salad Bowl (White)",
      descTr: "38 OZ en büyük hacimli beyaz kase modelimiz. Toplu yemek ve büyük porsiyon paket servisleri için sızdırmaz çözüm.",
      descEn: "38 OZ our largest volume white bowl model. Leak-proof solution for catering and large portion takeaways.",
      category: "white",
      volume: "38 OZ",
      imgMain: "./images/prods/38oz_white_main.webp",
      imgSub: "./images/prods/38oz_white_sub.webp",
      specs: {
        topDiameter: "185 mm",
        bottomDiameter: "160 mm",
        height: "60 mm",
        boxQty: "300 Adet / pcs",
        dimensions: "57*38*56 cm"
      }
    },
    {
      id: "prod-38oz-kraft",
      titleTr: "38 OZ Kraft Salata Kabı",
      titleEn: "38 OZ Kraft Salad Bowl",
      descTr: "38 OZ Kraft Salata Kabı, geniş kapasitesi ve doğal görünümüyle lüks restoranların bir numaralı tercihi.",
      descEn: "38 OZ Kraft Salad Bowl, the number one choice of luxury restaurants with its large capacity and natural look.",
      category: "kraft",
      volume: "38 OZ",
      imgMain: "./images/prods/38oz_kraft_main.webp",
      imgSub: "./images/prods/38oz_kraft_sub.webp",
      specs: {
        topDiameter: "185 mm",
        bottomDiameter: "160 mm",
        height: "60 mm",
        boxQty: "300 Adet / pcs",
        dimensions: "57*38*56 cm"
      }
    }
  ];
  
export const certificates = [
    { id: "cert1", titleTr: "ISO 22000 Gıda Güvenliği", titleEn: "ISO 22000 Food Safety", img: "./images/certs/cert1.webp" },
    { id: "cert2", titleTr: "FSC Orman Yönetimi", titleEn: "FSC Forest Management", img: "./images/certs/cert2.webp" },
    { id: "cert3", titleTr: "ISO 9001 Kalite Yönetimi", titleEn: "ISO 9001 Quality Management", img: "./images/certs/cert3.webp" },
    { id: "cert4", titleTr: "Helal Sertifikası", titleEn: "Halal Certificate", img: "./images/certs/cert4.webp" }
  ];
  
export const blogs = [
    {
      "id": "autonews-biopolymer-based-food-packaging-perform",
      "titleTr": "Gıda Ambalajında Son Gelişmeler: Biopolymer-based Gıda Ambalajı: performance, environmental impact, and pathways toward a Sürdürülebilir future - Frontiers",
      "titleEn": "Food Packaging Insights: Biopolymer-based food packaging: performance, environmental impact, and pathways toward a sustainable future - Frontiers",
      "date": "01 Eylül 2026",
      "author": "Kraften Ar-Ge",
      "category": "trendler",
      "img": "https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&w=800&q=80",
      "summaryTr": "Biopolymer-based Gıda Ambalajı: performance, environmental impact, and pathways toward a Sürdürülebilir future - Frontiers konusundaki en yeni küresel gıda ambalajı regülasyonları ve sürdürülebilir karton kaselerin avantajları.",
      "summaryEn": "Latest global packaging regulations on Biopolymer-based food packaging: performance, environmental impact, and pathways toward a sustainable future - Frontiers and advantages of sustainable paperboard containers.",
      "contentTr": "Küresel gıda ambalajı sektöründe Biopolymer-based Gıda Ambalajı: performance, environmental impact, and pathways toward a Sürdürülebilir future - Frontiers konusu hızla ön plana çıkmaktadır. Restoranların ve gıda üreticilerinin doğa dostu ambalajlara yönelimi, hem çevre sağlığını korumakta hem de markaların müşteri memnuniyetini yükseltmektedir.\n\nSon dönemde yayınlanan uluslararası regülasyonlar ve tüketici beklentileri, plastik türevli ambalajların yerine geri dönüştürülebilir ve gıdaya uygun sertifikalı kağıt ham maddelerinin geçmesini zorunlu kılmaktadır. Bu dönüşüm sadece çevresel sorumluluk değil, aynı zamanda işletmeler için stratejik bir marka yatırımıdır.\n\nKraften Ambalaj olarak, gıda temasına %100 uygun sertifikalı karton kaselerimiz ve yenilikçi AR-GE çözümlerimizle işletmelerin bu sürdürülebilirlik dönüşümüne öncülük ediyoruz.",
      "contentEn": "In the global food packaging sector, Biopolymer-based food packaging: performance, environmental impact, and pathways toward a sustainable future - Frontiers is rapidly coming to the forefront. The shift of restaurants towards eco-friendly packaging protects the environment while boosting customer trust.\n\nRecent environmental regulations and consumer demands necessitate replacing plastic food containers with recyclable paperboard raw materials. This transition is not only an environmental duty but also a strategic brand investment.\n\nAt Kraften Packaging, we lead the sustainability transformation of businesses through our certified paperboard containers."
},
    {
      "id": "autonews-coconut-based-bioplastic-targets-food-pa",
      "titleTr": "Gıda Ambalajında Son Gelişmeler: Coconut-based bioplastic targets Gıda Ambalajı waste - Ambalaj Insights",
      "titleEn": "Food Packaging Insights: Coconut-based bioplastic targets food packaging waste - Packaging Insights",
      "date": "31 Ağustos 2026",
      "author": "Kraften Ar-Ge",
      "category": "trendler",
      "img": "https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&w=800&q=80",
      "summaryTr": "Coconut-based bioplastic targets Gıda Ambalajı waste - Ambalaj Insights konusundaki en yeni küresel gıda ambalajı regülasyonları ve sürdürülebilir karton kaselerin avantajları.",
      "summaryEn": "Latest global packaging regulations on Coconut-based bioplastic targets food packaging waste - Packaging Insights and advantages of sustainable paperboard containers.",
      "contentTr": "Küresel gıda ambalajı sektöründe Coconut-based bioplastic targets Gıda Ambalajı waste - Ambalaj Insights konusu hızla ön plana çıkmaktadır. Restoranların ve gıda üreticilerinin doğa dostu ambalajlara yönelimi, hem çevre sağlığını korumakta hem de markaların müşteri memnuniyetini yükseltmektedir.\n\nSon dönemde yayınlanan uluslararası regülasyonlar ve tüketici beklentileri, plastik türevli ambalajların yerine geri dönüştürülebilir ve gıdaya uygun sertifikalı kağıt ham maddelerinin geçmesini zorunlu kılmaktadır. Bu dönüşüm sadece çevresel sorumluluk değil, aynı zamanda işletmeler için stratejik bir marka yatırımıdır.\n\nKraften Ambalaj olarak, gıda temasına %100 uygun sertifikalı karton kaselerimiz ve yenilikçi AR-GE çözümlerimizle işletmelerin bu sürdürülebilirlik dönüşümüne öncülük ediyoruz.",
      "contentEn": "In the global food packaging sector, Coconut-based bioplastic targets food packaging waste - Packaging Insights is rapidly coming to the forefront. The shift of restaurants towards eco-friendly packaging protects the environment while boosting customer trust.\n\nRecent environmental regulations and consumer demands necessitate replacing plastic food containers with recyclable paperboard raw materials. This transition is not only an environmental duty but also a strategic brand investment.\n\nAt Kraften Packaging, we lead the sustainability transformation of businesses through our certified paperboard containers."
},
    {
      "id": "autonews-uga-lab-turns-jellyfish-into-sustainable",
      "titleTr": "Gıda Ambalajında Son Gelişmeler: UGA Lab turns jellyfish into Sürdürülebilir food products - WUGA",
      "titleEn": "Food Packaging Insights: UGA Lab turns jellyfish into sustainable food products - WUGA",
      "date": "30 Ağustos 2026",
      "author": "Kraften Ar-Ge",
      "category": "trendler",
      "img": "https://images.unsplash.com/photo-1509099836639-18ba1795216d?auto=format&fit=crop&w=800&q=80",
      "summaryTr": "UGA Lab turns jellyfish into Sürdürülebilir food products - WUGA konusundaki en yeni küresel gıda ambalajı regülasyonları ve sürdürülebilir karton kaselerin avantajları.",
      "summaryEn": "Latest global packaging regulations on UGA Lab turns jellyfish into sustainable food products - WUGA and advantages of sustainable paperboard containers.",
      "contentTr": "Küresel gıda ambalajı sektöründe UGA Lab turns jellyfish into Sürdürülebilir food products - WUGA konusu hızla ön plana çıkmaktadır. Restoranların ve gıda üreticilerinin doğa dostu ambalajlara yönelimi, hem çevre sağlığını korumakta hem de markaların müşteri memnuniyetini yükseltmektedir.\n\nSon dönemde yayınlanan uluslararası regülasyonlar ve tüketici beklentileri, plastik türevli ambalajların yerine geri dönüştürülebilir ve gıdaya uygun sertifikalı kağıt ham maddelerinin geçmesini zorunlu kılmaktadır. Bu dönüşüm sadece çevresel sorumluluk değil, aynı zamanda işletmeler için stratejik bir marka yatırımıdır.\n\nKraften Ambalaj olarak, gıda temasına %100 uygun sertifikalı karton kaselerimiz ve yenilikçi AR-GE çözümlerimizle işletmelerin bu sürdürülebilirlik dönüşümüne öncülük ediyoruz.",
      "contentEn": "In the global food packaging sector, UGA Lab turns jellyfish into sustainable food products - WUGA is rapidly coming to the forefront. The shift of restaurants towards eco-friendly packaging protects the environment while boosting customer trust.\n\nRecent environmental regulations and consumer demands necessitate replacing plastic food containers with recyclable paperboard raw materials. This transition is not only an environmental duty but also a strategic brand investment.\n\nAt Kraften Packaging, we lead the sustainability transformation of businesses through our certified paperboard containers."
},
    {
      "id": "autonews-transforming-polyamide-microplastics-int",
      "titleTr": "Gıda Ambalajında Son Gelişmeler: Transforming polyamide microplastics into light-emitting carbon quantum dots for UV-blocking Gıda Ambalajı - Phys.org",
      "titleEn": "Food Packaging Insights: Transforming polyamide microplastics into light-emitting carbon quantum dots for UV-blocking food packaging - Phys.org",
      "date": "29 Ağustos 2026",
      "author": "Kraften Ar-Ge",
      "category": "trendler",
      "img": "https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?auto=format&fit=crop&w=800&q=80",
      "summaryTr": "Transforming polyamide microplastics into light-emitting carbon quantum dots for UV-blocking Gıda Ambalajı - Phys.org konusundaki en yeni küresel gıda ambalajı regülasyonları ve sürdürülebilir karton kaselerin avantajları.",
      "summaryEn": "Latest global packaging regulations on Transforming polyamide microplastics into light-emitting carbon quantum dots for UV-blocking food packaging - Phys.org and advantages of sustainable paperboard containers.",
      "contentTr": "Küresel gıda ambalajı sektöründe Transforming polyamide microplastics into light-emitting carbon quantum dots for UV-blocking Gıda Ambalajı - Phys.org konusu hızla ön plana çıkmaktadır. Restoranların ve gıda üreticilerinin doğa dostu ambalajlara yönelimi, hem çevre sağlığını korumakta hem de markaların müşteri memnuniyetini yükseltmektedir.\n\nSon dönemde yayınlanan uluslararası regülasyonlar ve tüketici beklentileri, plastik türevli ambalajların yerine geri dönüştürülebilir ve gıdaya uygun sertifikalı kağıt ham maddelerinin geçmesini zorunlu kılmaktadır. Bu dönüşüm sadece çevresel sorumluluk değil, aynı zamanda işletmeler için stratejik bir marka yatırımıdır.\n\nKraften Ambalaj olarak, gıda temasına %100 uygun sertifikalı karton kaselerimiz ve yenilikçi AR-GE çözümlerimizle işletmelerin bu sürdürülebilirlik dönüşümüne öncülük ediyoruz.",
      "contentEn": "In the global food packaging sector, Transforming polyamide microplastics into light-emitting carbon quantum dots for UV-blocking food packaging - Phys.org is rapidly coming to the forefront. The shift of restaurants towards eco-friendly packaging protects the environment while boosting customer trust.\n\nRecent environmental regulations and consumer demands necessitate replacing plastic food containers with recyclable paperboard raw materials. This transition is not only an environmental duty but also a strategic brand investment.\n\nAt Kraften Packaging, we lead the sustainability transformation of businesses through our certified paperboard containers."
},
    {
      "id": "autonews-alliedflex-smartsolve-collaborate-to-ad",
      "titleTr": "Gıda Ambalajında Son Gelişmeler: ALLIEDFLEX, SmartSolve collaborate to advance Sürdürülebilir flexible Ambalaj - Ambalaj Strategies",
      "titleEn": "Food Packaging Insights: ALLIEDFLEX, SmartSolve collaborate to advance sustainable flexible packaging - Packaging Strategies",
      "date": "28 Ağustos 2026",
      "author": "Kraften Ar-Ge",
      "category": "trendler",
      "img": "https://degisimpack.com/images/blogs/blog2.jpg",
      "summaryTr": "ALLIEDFLEX, SmartSolve collaborate to advance Sürdürülebilir flexible Ambalaj - Ambalaj Strategies konusundaki en yeni küresel gıda ambalajı regülasyonları ve sürdürülebilir karton kaselerin avantajları.",
      "summaryEn": "Latest global packaging regulations on ALLIEDFLEX, SmartSolve collaborate to advance sustainable flexible packaging - Packaging Strategies and advantages of sustainable paperboard containers.",
      "contentTr": "Küresel gıda ambalajı sektöründe ALLIEDFLEX, SmartSolve collaborate to advance Sürdürülebilir flexible Ambalaj - Ambalaj Strategies konusu hızla ön plana çıkmaktadır. Restoranların ve gıda üreticilerinin doğa dostu ambalajlara yönelimi, hem çevre sağlığını korumakta hem de markaların müşteri memnuniyetini yükseltmektedir.\n\nSon dönemde yayınlanan uluslararası regülasyonlar ve tüketici beklentileri, plastik türevli ambalajların yerine geri dönüştürülebilir ve gıdaya uygun sertifikalı kağıt ham maddelerinin geçmesini zorunlu kılmaktadır. Bu dönüşüm sadece çevresel sorumluluk değil, aynı zamanda işletmeler için stratejik bir marka yatırımıdır.\n\nKraften Ambalaj olarak, gıda temasına %100 uygun sertifikalı karton kaselerimiz ve yenilikçi AR-GE çözümlerimizle işletmelerin bu sürdürülebilirlik dönüşümüne öncülük ediyoruz.",
      "contentEn": "In the global food packaging sector, ALLIEDFLEX, SmartSolve collaborate to advance sustainable flexible packaging - Packaging Strategies is rapidly coming to the forefront. The shift of restaurants towards eco-friendly packaging protects the environment while boosting customer trust.\n\nRecent environmental regulations and consumer demands necessitate replacing plastic food containers with recyclable paperboard raw materials. This transition is not only an environmental duty but also a strategic brand investment.\n\nAt Kraften Packaging, we lead the sustainability transformation of businesses through our certified paperboard containers."
},
    {
      "id": "autonews-ahlstrom-launches-new-food-packaging-pap",
      "titleTr": "Gıda Ambalajında Son Gelişmeler: Ahlstrom launches new Gıda Ambalajı papers - PULPAPERnews.com",
      "titleEn": "Food Packaging Insights: Ahlstrom launches new food packaging papers - PULPAPERnews.com",
      "date": "27 Ağustos 2026",
      "author": "Kraften Ar-Ge",
      "category": "trendler",
      "img": "https://degisimpack.com/images/blogs/blog2.jpg",
      "summaryTr": "Ahlstrom launches new Gıda Ambalajı papers - PULPAPERnews.com konusundaki en yeni küresel gıda ambalajı regülasyonları ve sürdürülebilir karton kaselerin avantajları.",
      "summaryEn": "Latest global packaging regulations on Ahlstrom launches new food packaging papers - PULPAPERnews.com and advantages of sustainable paperboard containers.",
      "contentTr": "Küresel gıda ambalajı sektöründe Ahlstrom launches new Gıda Ambalajı papers - PULPAPERnews.com konusu hızla ön plana çıkmaktadır. Restoranların ve gıda üreticilerinin doğa dostu ambalajlara yönelimi, hem çevre sağlığını korumakta hem de markaların müşteri memnuniyetini yükseltmektedir.\n\nSon dönemde yayınlanan uluslararası regülasyonlar ve tüketici beklentileri, plastik türevli ambalajların yerine geri dönüştürülebilir ve gıdaya uygun sertifikalı kağıt ham maddelerinin geçmesini zorunlu kılmaktadır. Bu dönüşüm sadece çevresel sorumluluk değil, aynı zamanda işletmeler için stratejik bir marka yatırımıdır.\n\nKraften Ambalaj olarak, gıda temasına %100 uygun sertifikalı karton kaselerimiz ve yenilikçi AR-GE çözümlerimizle işletmelerin bu sürdürülebilirlik dönüşümüne öncülük ediyoruz.",
      "contentEn": "In the global food packaging sector, Ahlstrom launches new food packaging papers - PULPAPERnews.com is rapidly coming to the forefront. The shift of restaurants towards eco-friendly packaging protects the environment while boosting customer trust.\n\nRecent environmental regulations and consumer demands necessitate replacing plastic food containers with recyclable paperboard raw materials. This transition is not only an environmental duty but also a strategic brand investment.\n\nAt Kraften Packaging, we lead the sustainability transformation of businesses through our certified paperboard containers."
},
    {
      "id": "autonews-wepsea-2026-to-spotlight-indonesias-sus",
      "titleTr": "Gıda Ambalajında Son Gelişmeler: WEPSEA 2026 to Spotlight Indonesia's Sürdürülebilir Gıda Ambalajı Pazar Analizi with Pulp Molding Forum Connecting Brands and the Ambalaj Supply Chain - PR Newswire",
      "titleEn": "Food Packaging Insights: WEPSEA 2026 to Spotlight Indonesia's Sustainable Food Packaging Market with Pulp Molding Forum Connecting Brands and the Packaging Supply Chain - PR Newswire",
      "date": "26 Ağustos 2026",
      "author": "Kraften Ar-Ge",
      "category": "trendler",
      "img": "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=800&q=80",
      "summaryTr": "WEPSEA 2026 to Spotlight Indonesia's Sürdürülebilir Gıda Ambalajı Pazar Analizi with Pulp Molding Forum Connecting Brands and the Ambalaj Supply Chain - PR Newswire konusundaki en yeni küresel gıda ambalajı regülasyonları ve sürdürülebilir karton kaselerin avantajları.",
      "summaryEn": "Latest global packaging regulations on WEPSEA 2026 to Spotlight Indonesia's Sustainable Food Packaging Market with Pulp Molding Forum Connecting Brands and the Packaging Supply Chain - PR Newswire and advantages of sustainable paperboard containers.",
      "contentTr": "Küresel gıda ambalajı sektöründe WEPSEA 2026 to Spotlight Indonesia's Sürdürülebilir Gıda Ambalajı Pazar Analizi with Pulp Molding Forum Connecting Brands and the Ambalaj Supply Chain - PR Newswire konusu hızla ön plana çıkmaktadır. Restoranların ve gıda üreticilerinin doğa dostu ambalajlara yönelimi, hem çevre sağlığını korumakta hem de markaların müşteri memnuniyetini yükseltmektedir.\n\nSon dönemde yayınlanan uluslararası regülasyonlar ve tüketici beklentileri, plastik türevli ambalajların yerine geri dönüştürülebilir ve gıdaya uygun sertifikalı kağıt ham maddelerinin geçmesini zorunlu kılmaktadır. Bu dönüşüm sadece çevresel sorumluluk değil, aynı zamanda işletmeler için stratejik bir marka yatırımıdır.\n\nKraften Ambalaj olarak, gıda temasına %100 uygun sertifikalı karton kaselerimiz ve yenilikçi AR-GE çözümlerimizle işletmelerin bu sürdürülebilirlik dönüşümüne öncülük ediyoruz.",
      "contentEn": "In the global food packaging sector, WEPSEA 2026 to Spotlight Indonesia's Sustainable Food Packaging Market with Pulp Molding Forum Connecting Brands and the Packaging Supply Chain - PR Newswire is rapidly coming to the forefront. The shift of restaurants towards eco-friendly packaging protects the environment while boosting customer trust.\n\nRecent environmental regulations and consumer demands necessitate replacing plastic food containers with recyclable paperboard raw materials. This transition is not only an environmental duty but also a strategic brand investment.\n\nAt Kraften Packaging, we lead the sustainability transformation of businesses through our certified paperboard containers."
},
    {
      "id": "autonews-pfas-free-food-packaging-market-opportun",
      "titleTr": "Gıda Ambalajında Son Gelişmeler: Zararlı Kimyasal İçermeyen Gıda Ambalajı Pazar Analizi Opportunity Forecast 2026-2035 | Regulatory Momentum and Sustainability Demand Accelerate Zararlı Kimyasal İçermeyen Gıda Ambalajı - Yahoo! Finance Canada",
      "titleEn": "Food Packaging Insights: PFAS-Free Food Packaging Market Opportunity Forecast 2026-2035 | Regulatory Momentum and Sustainability Demand Accelerate PFAS-Free Food Packaging - Yahoo! Finance Canada",
      "date": "25 Ağustos 2026",
      "author": "Kraften Ar-Ge",
      "category": "trendler",
      "img": "https://degisimpack.com/images/blogs/blog4.jpg",
      "summaryTr": "Zararlı Kimyasal İçermeyen Gıda Ambalajı Pazar Analizi Opportunity Forecast 2026-2035 | Regulatory Momentum and Sustainability Demand Accelerate Zararlı Kimyasal İçermeyen Gıda Ambalajı - Yahoo! Finance Canada konusundaki en yeni küresel gıda ambalajı regülasyonları ve sürdürülebilir karton kaselerin avantajları.",
      "summaryEn": "Latest global packaging regulations on PFAS-Free Food Packaging Market Opportunity Forecast 2026-2035 | Regulatory Momentum and Sustainability Demand Accelerate PFAS-Free Food Packaging - Yahoo! Finance Canada and advantages of sustainable paperboard containers.",
      "contentTr": "Küresel gıda ambalajı sektöründe Zararlı Kimyasal İçermeyen Gıda Ambalajı Pazar Analizi Opportunity Forecast 2026-2035 | Regulatory Momentum and Sustainability Demand Accelerate Zararlı Kimyasal İçermeyen Gıda Ambalajı - Yahoo! Finance Canada konusu hızla ön plana çıkmaktadır. Restoranların ve gıda üreticilerinin doğa dostu ambalajlara yönelimi, hem çevre sağlığını korumakta hem de markaların müşteri memnuniyetini yükseltmektedir.\n\nSon dönemde yayınlanan uluslararası regülasyonlar ve tüketici beklentileri, plastik türevli ambalajların yerine geri dönüştürülebilir ve gıdaya uygun sertifikalı kağıt ham maddelerinin geçmesini zorunlu kılmaktadır. Bu dönüşüm sadece çevresel sorumluluk değil, aynı zamanda işletmeler için stratejik bir marka yatırımıdır.\n\nKraften Ambalaj olarak, gıda temasına %100 uygun sertifikalı karton kaselerimiz ve yenilikçi AR-GE çözümlerimizle işletmelerin bu sürdürülebilirlik dönüşümüne öncülük ediyoruz.",
      "contentEn": "In the global food packaging sector, PFAS-Free Food Packaging Market Opportunity Forecast 2026-2035 | Regulatory Momentum and Sustainability Demand Accelerate PFAS-Free Food Packaging - Yahoo! Finance Canada is rapidly coming to the forefront. The shift of restaurants towards eco-friendly packaging protects the environment while boosting customer trust.\n\nRecent environmental regulations and consumer demands necessitate replacing plastic food containers with recyclable paperboard raw materials. This transition is not only an environmental duty but also a strategic brand investment.\n\nAt Kraften Packaging, we lead the sustainability transformation of businesses through our certified paperboard containers."
},
    {
      "id": "autonews-navigating-sustainability-in-the-food-an",
      "titleTr": "Gıda Ambalajında Son Gelişmeler: Navigating Sustainability in the Food and Beverage Industry - Ambalaj Strategies",
      "titleEn": "Food Packaging Insights: Navigating Sustainability in the Food and Beverage Industry - Packaging Strategies",
      "date": "24 Ağustos 2026",
      "author": "Kraften Ar-Ge",
      "category": "trendler",
      "img": "https://degisimpack.com/images/blogs/blog2.jpg",
      "summaryTr": "Navigating Sustainability in the Food and Beverage Industry - Ambalaj Strategies konusundaki en yeni küresel gıda ambalajı regülasyonları ve sürdürülebilir karton kaselerin avantajları.",
      "summaryEn": "Latest global packaging regulations on Navigating Sustainability in the Food and Beverage Industry - Packaging Strategies and advantages of sustainable paperboard containers.",
      "contentTr": "Küresel gıda ambalajı sektöründe Navigating Sustainability in the Food and Beverage Industry - Ambalaj Strategies konusu hızla ön plana çıkmaktadır. Restoranların ve gıda üreticilerinin doğa dostu ambalajlara yönelimi, hem çevre sağlığını korumakta hem de markaların müşteri memnuniyetini yükseltmektedir.\n\nSon dönemde yayınlanan uluslararası regülasyonlar ve tüketici beklentileri, plastik türevli ambalajların yerine geri dönüştürülebilir ve gıdaya uygun sertifikalı kağıt ham maddelerinin geçmesini zorunlu kılmaktadır. Bu dönüşüm sadece çevresel sorumluluk değil, aynı zamanda işletmeler için stratejik bir marka yatırımıdır.\n\nKraften Ambalaj olarak, gıda temasına %100 uygun sertifikalı karton kaselerimiz ve yenilikçi AR-GE çözümlerimizle işletmelerin bu sürdürülebilirlik dönüşümüne öncülük ediyoruz.",
      "contentEn": "In the global food packaging sector, Navigating Sustainability in the Food and Beverage Industry - Packaging Strategies is rapidly coming to the forefront. The shift of restaurants towards eco-friendly packaging protects the environment while boosting customer trust.\n\nRecent environmental regulations and consumer demands necessitate replacing plastic food containers with recyclable paperboard raw materials. This transition is not only an environmental duty but also a strategic brand investment.\n\nAt Kraften Packaging, we lead the sustainability transformation of businesses through our certified paperboard containers."
},
    {
      "id": "autonews-study-explores-the-development-of-biodeg",
      "titleTr": "Gıda Ambalajında Son Gelişmeler: Study explores the development of biodegradable Gıda Ambalajı from rapeseed waste - Sustainability Online",
      "titleEn": "Food Packaging Insights: Study explores the development of biodegradable food packaging from rapeseed waste - Sustainability Online",
      "date": "23 Ağustos 2026",
      "author": "Kraften Ar-Ge",
      "category": "trendler",
      "img": "https://images.unsplash.com/photo-1509099836639-18ba1795216d?auto=format&fit=crop&w=800&q=80",
      "summaryTr": "Study explores the development of biodegradable Gıda Ambalajı from rapeseed waste - Sustainability Online konusundaki en yeni küresel gıda ambalajı regülasyonları ve sürdürülebilir karton kaselerin avantajları.",
      "summaryEn": "Latest global packaging regulations on Study explores the development of biodegradable food packaging from rapeseed waste - Sustainability Online and advantages of sustainable paperboard containers.",
      "contentTr": "Küresel gıda ambalajı sektöründe Study explores the development of biodegradable Gıda Ambalajı from rapeseed waste - Sustainability Online konusu hızla ön plana çıkmaktadır. Restoranların ve gıda üreticilerinin doğa dostu ambalajlara yönelimi, hem çevre sağlığını korumakta hem de markaların müşteri memnuniyetini yükseltmektedir.\n\nSon dönemde yayınlanan uluslararası regülasyonlar ve tüketici beklentileri, plastik türevli ambalajların yerine geri dönüştürülebilir ve gıdaya uygun sertifikalı kağıt ham maddelerinin geçmesini zorunlu kılmaktadır. Bu dönüşüm sadece çevresel sorumluluk değil, aynı zamanda işletmeler için stratejik bir marka yatırımıdır.\n\nKraften Ambalaj olarak, gıda temasına %100 uygun sertifikalı karton kaselerimiz ve yenilikçi AR-GE çözümlerimizle işletmelerin bu sürdürülebilirlik dönüşümüne öncülük ediyoruz.",
      "contentEn": "In the global food packaging sector, Study explores the development of biodegradable food packaging from rapeseed waste - Sustainability Online is rapidly coming to the forefront. The shift of restaurants towards eco-friendly packaging protects the environment while boosting customer trust.\n\nRecent environmental regulations and consumer demands necessitate replacing plastic food containers with recyclable paperboard raw materials. This transition is not only an environmental duty but also a strategic brand investment.\n\nAt Kraften Packaging, we lead the sustainability transformation of businesses through our certified paperboard containers."
},
    {
      "id": "autonews-flexible-packaging-innovations-drive-sus",
      "titleTr": "Gıda Ambalajında Son Gelişmeler: Flexible Ambalaj innovations drive sustainability - PlasticsToday",
      "titleEn": "Food Packaging Insights: Flexible packaging innovations drive sustainability - PlasticsToday",
      "date": "22 Ağustos 2026",
      "author": "Kraften Ar-Ge",
      "category": "trendler",
      "img": "https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?auto=format&fit=crop&w=800&q=80",
      "summaryTr": "Flexible Ambalaj innovations drive sustainability - PlasticsToday konusundaki en yeni küresel gıda ambalajı regülasyonları ve sürdürülebilir karton kaselerin avantajları.",
      "summaryEn": "Latest global packaging regulations on Flexible packaging innovations drive sustainability - PlasticsToday and advantages of sustainable paperboard containers.",
      "contentTr": "Küresel gıda ambalajı sektöründe Flexible Ambalaj innovations drive sustainability - PlasticsToday konusu hızla ön plana çıkmaktadır. Restoranların ve gıda üreticilerinin doğa dostu ambalajlara yönelimi, hem çevre sağlığını korumakta hem de markaların müşteri memnuniyetini yükseltmektedir.\n\nSon dönemde yayınlanan uluslararası regülasyonlar ve tüketici beklentileri, plastik türevli ambalajların yerine geri dönüştürülebilir ve gıdaya uygun sertifikalı kağıt ham maddelerinin geçmesini zorunlu kılmaktadır. Bu dönüşüm sadece çevresel sorumluluk değil, aynı zamanda işletmeler için stratejik bir marka yatırımıdır.\n\nKraften Ambalaj olarak, gıda temasına %100 uygun sertifikalı karton kaselerimiz ve yenilikçi AR-GE çözümlerimizle işletmelerin bu sürdürülebilirlik dönüşümüne öncülük ediyoruz.",
      "contentEn": "In the global food packaging sector, Flexible packaging innovations drive sustainability - PlasticsToday is rapidly coming to the forefront. The shift of restaurants towards eco-friendly packaging protects the environment while boosting customer trust.\n\nRecent environmental regulations and consumer demands necessitate replacing plastic food containers with recyclable paperboard raw materials. This transition is not only an environmental duty but also a strategic brand investment.\n\nAt Kraften Packaging, we lead the sustainability transformation of businesses through our certified paperboard containers."
},
    {
      "id": "autonews-infographic-packaging-facilities-lead",
      "titleTr": "Gıda Ambalajında Son Gelişmeler: Infographic: Ambalaj, facilities lead 41 pet food Şirketler ve Trendler’ sustainability initiatives - PetfoodIndustry",
      "titleEn": "Food Packaging Insights: Infographic: Packaging, facilities lead 41 pet food companies’ sustainability initiatives - PetfoodIndustry",
      "date": "21 Ağustos 2026",
      "author": "Kraften Ar-Ge",
      "category": "trendler",
      "img": "https://images.unsplash.com/photo-1509099836639-18ba1795216d?auto=format&fit=crop&w=800&q=80",
      "summaryTr": "Infographic: Ambalaj, facilities lead 41 pet food Şirketler ve Trendler’ sustainability initiatives - PetfoodIndustry konusundaki en yeni küresel gıda ambalajı regülasyonları ve sürdürülebilir karton kaselerin avantajları.",
      "summaryEn": "Latest global packaging regulations on Infographic: Packaging, facilities lead 41 pet food companies’ sustainability initiatives - PetfoodIndustry and advantages of sustainable paperboard containers.",
      "contentTr": "Küresel gıda ambalajı sektöründe Infographic: Ambalaj, facilities lead 41 pet food Şirketler ve Trendler’ sustainability initiatives - PetfoodIndustry konusu hızla ön plana çıkmaktadır. Restoranların ve gıda üreticilerinin doğa dostu ambalajlara yönelimi, hem çevre sağlığını korumakta hem de markaların müşteri memnuniyetini yükseltmektedir.\n\nSon dönemde yayınlanan uluslararası regülasyonlar ve tüketici beklentileri, plastik türevli ambalajların yerine geri dönüştürülebilir ve gıdaya uygun sertifikalı kağıt ham maddelerinin geçmesini zorunlu kılmaktadır. Bu dönüşüm sadece çevresel sorumluluk değil, aynı zamanda işletmeler için stratejik bir marka yatırımıdır.\n\nKraften Ambalaj olarak, gıda temasına %100 uygun sertifikalı karton kaselerimiz ve yenilikçi AR-GE çözümlerimizle işletmelerin bu sürdürülebilirlik dönüşümüne öncülük ediyoruz.",
      "contentEn": "In the global food packaging sector, Infographic: Packaging, facilities lead 41 pet food companies’ sustainability initiatives - PetfoodIndustry is rapidly coming to the forefront. The shift of restaurants towards eco-friendly packaging protects the environment while boosting customer trust.\n\nRecent environmental regulations and consumer demands necessitate replacing plastic food containers with recyclable paperboard raw materials. This transition is not only an environmental duty but also a strategic brand investment.\n\nAt Kraften Packaging, we lead the sustainability transformation of businesses through our certified paperboard containers."
},
    {
      "id": "autonews-sustainable-food-packaging-company-with",
      "titleTr": "Gıda Ambalajında Son Gelişmeler: Sürdürülebilir Gıda Ambalajı Company With Indian Roots to Invest $5M Gainesville - Global Atlanta",
      "titleEn": "Food Packaging Insights: Sustainable Food Packaging Company With Indian Roots to Invest $5M Gainesville - Global Atlanta",
      "date": "20 Ağustos 2026",
      "author": "Kraften Ar-Ge",
      "category": "trendler",
      "img": "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=800&q=80",
      "summaryTr": "Sürdürülebilir Gıda Ambalajı Company With Indian Roots to Invest $5M Gainesville - Global Atlanta konusundaki en yeni küresel gıda ambalajı regülasyonları ve sürdürülebilir karton kaselerin avantajları.",
      "summaryEn": "Latest global packaging regulations on Sustainable Food Packaging Company With Indian Roots to Invest $5M Gainesville - Global Atlanta and advantages of sustainable paperboard containers.",
      "contentTr": "Küresel gıda ambalajı sektöründe Sürdürülebilir Gıda Ambalajı Company With Indian Roots to Invest $5M Gainesville - Global Atlanta konusu hızla ön plana çıkmaktadır. Restoranların ve gıda üreticilerinin doğa dostu ambalajlara yönelimi, hem çevre sağlığını korumakta hem de markaların müşteri memnuniyetini yükseltmektedir.\n\nSon dönemde yayınlanan uluslararası regülasyonlar ve tüketici beklentileri, plastik türevli ambalajların yerine geri dönüştürülebilir ve gıdaya uygun sertifikalı kağıt ham maddelerinin geçmesini zorunlu kılmaktadır. Bu dönüşüm sadece çevresel sorumluluk değil, aynı zamanda işletmeler için stratejik bir marka yatırımıdır.\n\nKraften Ambalaj olarak, gıda temasına %100 uygun sertifikalı karton kaselerimiz ve yenilikçi AR-GE çözümlerimizle işletmelerin bu sürdürülebilirlik dönüşümüne öncülük ediyoruz.",
      "contentEn": "In the global food packaging sector, Sustainable Food Packaging Company With Indian Roots to Invest $5M Gainesville - Global Atlanta is rapidly coming to the forefront. The shift of restaurants towards eco-friendly packaging protects the environment while boosting customer trust.\n\nRecent environmental regulations and consumer demands necessitate replacing plastic food containers with recyclable paperboard raw materials. This transition is not only an environmental duty but also a strategic brand investment.\n\nAt Kraften Packaging, we lead the sustainability transformation of businesses through our certified paperboard containers."
},
    {
      "id": "autonews-sustainable-food-packaging-in-2045-the",
      "titleTr": "2045 Geleceğin Sürdürülebilir Gıda Ambalajı Trendleri ve İnovasyonlar",
      "titleEn": "Sustainable Food Packaging in 2045: The Shape of Things to Come",
      "date": "17 Ağustos 2026",
      "author": "Kraften Ar-Ge",
      "category": "trendler",
      "img": "https://degisimpack.com/images/blogs/blog2.jpg",
      "summaryTr": "Smithers küresel ambalaj raporuna göre 2045 yılına kadar gıda ambalajı sektörünü şekillendirecek sıfır atık ve sürdürülebilir karton kaplama teknolojileri.",
      "summaryEn": "Global packaging insights on zero-waste and sustainable paperboard container technologies shaping the future of food service.",
      "contentTr": "Küresel gıda ambalajı sektöründe 2045 vizyonu ve sürdürülebilir ambalaj teknolojileri konusu hızla ön plana çıkmaktadır. Restoranların ve gıda üreticilerinin doğa dostu ambalajlara yönelimi, hem çevre sağlığını korumakta hem de markaların müşteri memnuniyetini yükseltmektedir.\n\nSon dönemde yayınlanan uluslararası regülasyonlar ve tüketici beklentileri, plastik türevli ambalajların yerine geri dönüştürülebilir ve gıdaya uygun sertifikalı kağıt ham maddelerinin geçmesini zorunlu kılmaktadır. Bu dönüşüm sadece çevresel sorumluluk değil, aynı zamanda işletmeler için stratejik bir marka yatırımıdır.\n\nKraften Ambalaj olarak, gıda temasına %100 uygun sertifikalı karton kaselerimiz ve yenilikçi AR-GE çözümlerimizle işletmelerin bu sürdürülebilirlik dönüşümüne öncülük ediyoruz.",
      "contentEn": "In the global food packaging sector, sustainable food packaging is rapidly coming to the forefront. The shift of restaurants towards eco-friendly packaging protects the environment while boosting customer trust.\n\nRecent environmental regulations and consumer demands necessitate replacing plastic food containers with recyclable paperboard raw materials. This transition is not only an environmental duty but also a strategic brand investment.\n\nAt Kraften Packaging, we lead the sustainability transformation of businesses through our certified paperboard containers."
},
    {
      "id": "autonews-top-pfas-free-food-packaging-companies",
      "titleTr": "Zararlı Kimyasal İçermeyen (PFAS-Free) Gıda Ambalajlarında Küresel Büyüme",
      "titleEn": "Top PFAS-Free Food Packaging Companies & Global Market Growth",
      "date": "17 Ağustos 2026",
      "author": "Kraften Ar-Ge",
      "category": "hijyen",
      "img": "https://degisimpack.com/images/blogs/blog4.jpg",
      "summaryTr": "Fortune Business Insights araştırmasına göre gıda ile temasa uygun, zararlı kimyasal barındırmayan kağıt kapların pazar payı yıllık %6.54 büyüyor.",
      "summaryEn": "Research on food-contact safe, chemical-free paper containers growing rapidly worldwide.",
      "contentTr": "Küresel gıda güvenliği standartlarında PFAS ve zararlı kaplama kimyasallarından arındırılmış ambalaj çözümleri ön plana çıkmaktadır. Restoranların ve gıda üreticilerinin doğa dostu ve insan sağlığına %100 zararsız ambalajlara yönelimi, markaların müşteri güvenini katlamaktadır.\n\nKraften Ambalaj olarak, gıda temasına %100 uygun ISO 22000 ve FSC sertifikalı karton kaselerimiz ve yenilikçi AR-GE çözümlerimizle işletmelerin sürdürülebilirlik dönüşümüne öncülük ediyoruz.",
      "contentEn": "In the global food packaging sector, chemical-free food-contact safe packaging is rapidly coming to the forefront."
},
    {
      id: "cevre-dostu-geri-donusum",
      titleTr: "Çevre Dostu Geri Dönüşüm ve Kraft Ambalajın Geleceği",
      titleEn: "Eco-Friendly Recycling and Future of Kraft Packaging",
      date: "14 Ağustos 2026",
      author: "Kraften Ambalaj",
      category: "trendler",
      img: "https://degisimpack.com/images/blogs/blog1.jpg",
      summaryTr: "Karton gıda kaplarımız %99 geri dönüştürülebilir yapısıyla atık miktarını en aza indirir. Gıda sektöründe kraft kullanımının avantajlarını keşfedin.",
      summaryEn: "Our paper food containers minimize waste with 99% recyclability. Discover the benefits of kraft packaging in the food sector.",
      contentTr: "Kraften Ambalaj olarak çevre dostu bir yaklaşımla tedarik edilen karton gıda kaplarımız, atıkların %99'ünün geri dönüştürülebilir olmasıyla çevre için hayati bir adım atıyor. Plastik türevli ambalajlara kıyasla doğada kat kat hızlı çözünen kraft ve selüloz lifleri, sürdürülebilir bir gelecek için restoranların ve paket servislerin en güçlü tercihi haline gelmiştir."
    },
    {
      id: "hizli-biyolojik-cozunurluk",
      titleTr: "Hızlı Biyolojik Çözünürlük ile Doğayı Koru",
      titleEn: "Protect Nature with Rapid Biodegradability",
      date: "02 Ağustos 2026",
      author: "Kraften Ambalaj",
      category: "surdurulebilirlik",
      img: "https://degisimpack.com/images/blogs/blog2.jpg",
      summaryTr: "Doğada parça kalıntısı bırakmadan hızlıca yok olan kraft liflerinin ekolojik dengeye katkısı.",
      summaryEn: "How natural kraft fibers decompose quickly without microplastic residue for ecological balance.",
      contentTr: "Karton gıda kaplarımızın benzersiz özelliği olan hızlı biyolojik çözünürlük ile doğaya yük olmadan pratik ambalaj sunuyoruz. Doğal dökülen ağaç liflerinden ve sertifikalı ormanlardan elde edilen kağıt kaselerimiz, toprakta mikroplastik kalıntı bırakmaz ve doğaya tamamen karışır."
    },
    {
      id: "hijyen-standartlari",
      titleTr: "Gıda Ambalajında Uluslararası Hijyen Standartları",
      titleEn: "International Hygiene Standards in Food Packaging",
      date: "25 Temmuz 2026",
      author: "Kraften Ambalaj",
      category: "hijyen",
      img: "https://degisimpack.com/images/blogs/blog4.jpg",
      summaryTr: "Sıcak ve soğuk gıda temasında zararlı kanserojen madde içermeyen ISO 22000 onaylı hijyen koşulları.",
      summaryEn: "ISO 22000 approved hygienic conditions free from harmful carcinogens in hot and cold food packaging.",
      contentTr: "Ürünlerimizin üretim süreci en yüksek hijyen standartlarına uygun olarak gerçekleştirilir. Sıcak çorbalardan asitli ve soslu salatalara kadar tüm gıdaların yapısını koruyan kaplamalarımız tamamen gıdaya uygun sertifikalıdır."
    },
    {
      id: "avrupa-birligi-plastik-yasagi",
      titleTr: "Avrupa Birliği Tek Kullanımlık Plastik Yasağı ve Ambalaj Sektörü",
      titleEn: "EU Single-Use Plastics Ban and Impact on Packaging Industry",
      date: "18 Temmuz 2026",
      author: "Kraften Ar-Ge",
      category: "trendler",
      img: "https://degisimpack.com/images/blogs/blog1.jpg",
      summaryTr: "AB çevre regülasyonlarının ihracatçı gıda firmalarına getirdiği yeni zorunluluklar ve kraft karton çözümleri.",
      summaryEn: "New requirements of EU environmental regulations for food exporters and kraft paperboard solutions.",
      contentTr: "Avrupa Birliği'nin tek kullanımlık plastik ürünlere getirdiği sert kısıtlamalar, uluslararası gıda ihracatı yapan Türk restoran ve markaları için karton ambalajı zorunlu kılmıştır. Kraften Ambalaj çözümleri AB standartlarına %100 uyumludur."
    },
    {
      id: "paket-serviste-lezzet-koruma",
      titleTr: "Paket Serviste Sıcaklık ve Nem Dengesi Nasıl Korunur?",
      titleEn: "Maintaining Temperature and Moisture Balance in Food Delivery",
      date: "10 Temmuz 2026",
      author: "Kraften Akademi",
      category: "hijyen",
      img: "https://degisimpack.com/images/blogs/blog2.jpg",
      summaryTr: "Özel tasarlanmış buhar tahliye delikli kapaklar ve termos özellikli karton kaseler ile sipariş kalitesini artırın.",
      summaryEn: "Enhance order quality with specially designed steam-vented lids and thermo-insulated paper bowls.",
      contentTr: "Paket serviste yemeğin terleme yapıp yumuşaması müşterilerin en büyük şikayetidir. Kraften'in özel kapağı ve yüksek gramajlı karton duvarları, iç sıcaklığı korurken buharı kontrollü tahliye eder."
    }
  ];
  
export const translations = {
    tr: {
      brand: "KRAFTEN AMBALAJ",
      tagline: "Yenilikçi Ambalaj, Çevre Dostu Gelecek",
      navHome: "ANASAYFA",
      navVision: "VİZYON",
      navProducts: "ENDÜSTRİYEL ÇÖZÜMLER",
      navCertificates: "SERTİFİKALAR",
      navBlog: "BLOG",
      navSustainability: "SÜRDÜRÜLEBİLİRLİK",
      navContactBtn: "İLETİŞİME GEÇİN",
      heroSubtitle: "GLOBAL PACKAGING INDUSTRY",
      heroTitle: "Mükemmelliği<br>Yeniden Tanımlıyoruz.",
      heroDesc: "Uluslararası gıda güvenliği standartlarında, doğadan ilham alan inovatif ambalaj çözümleri.",
      heroBtn: "Çözümleri Keşfedin",
      visionHeading: "Geleceği Şekillendiriyoruz",
      visionBody: "Kraften Ambalaj olarak, sadece ambalaj üretmiyor; çevre dostu ve %99 geri dönüştürülebilir ham maddelerle endüstriyel ekosistemi yeniden inşa ediyoruz. Kalite, hijyen ve prestij bizim DNA'mızda var.",
      statEco: "Geri Dönüştürülebilir",
      statIso: "22000 Standartları",
      statFsc: "Sertifikalı Üretim",
      statExport: "30+ Ülkeye İhracat",
      btnCatalog: "E-Katalog (PDF)",
      btnSample: "Ücretsiz Numune İsteyin",
      sampleModalTitle: "Kurumsal Ücretsiz Numune Talebi",
      sampleModalDesc: "İşletmeniz için kağıt gramajı ve gıda temasına uygun ürün numunelerimizi adresinize gönderelim.",
      sampleCompany: "Firma / İşletme Adı *",
      sampleName: "Yetkili Adı Soyadı *",
      samplePhone: "Telefon / WhatsApp *",
      sampleProduct: "İlgilendiğiniz Ürün Grubu",
      sampleAddress: "Teslimat Adresi *",
      btnSubmitSample: "Numune Talebini Gönder",
      waWidgetText: "Hızlı Teklif & WhatsApp",
      prodSub: "PREMIUM GIDA KAPLARI",
      prodHeading: "Endüstriyel Ürün Gamı",
      allCategories: "Tüm Kategoriler",
      searchPlaceholder: "Ürün ara (Örn: Kraft, 550 CC)...",
      specTitle: "Teknik Özellikler",
      topDiameter: "Ağız Çapı",
      bottomDiameter: "Taban Çapı",
      height: "Yükseklik",
      volume: "Hacim",
      boxQty: "Koli İçi Adet",
      boxDimensions: "Koli Ölçüsü (G*U*Y)",
      btnWhatsappQuote: "WhatsApp ile Sipariş & Teklif Al",
      certTitle: "Uluslararası Akreditasyon",
      certSub: "Dağıtımını üstlendiğimiz tüm gıda ambalajları FSC ve gıda temasına uygundur.",
      blogTitle: "Sektörel Haberler & Makaleler",
      blogViewAll: "Tüm Haberleri İncele →",
      blogHeroSubtitle: "KRAFTEN INSIGHTS & NEWS",
      blogHeroTitle: "Ambalaj Dünyasından<br>Güncel Makaleler",
      blogSearchPlaceholder: "Haber veya makale ara...",
      blogBackToHome: "← Anasayfaya Dön",
      readMore: "Devamını Oku →",
      susTitle: "Sıfır Karbon İzi Hedefi.",
      susDesc: "Üretim hatlarımızdan son tüketiciye kadar her adımda doğayı korumaya yeminliyiz. Plastik tüketimini azaltan yenilikçi Ar-Ge yatırımlarımızla sektörde öncüyüz.",
      susBtn: "Sürdürülebilirlik Raporu",
      footerDesc: "Yenilikçi ve sürdürülebilir ambalaj çözümleri.",
      adminTitle: "Kraften - Üst Düzey Yönetim Paneli",
      adminAddCategory: "Yeni Kategori Ekle",
      adminAddProduct: "Yeni Ürün Ekle",
      adminCategoryNameTr: "Kategori Adı (TR)",
      adminCategoryNameEn: "Kategori Adı (EN)",
      adminProductTitleTr: "Ürün Başlığı (TR)",
      adminProductTitleEn: "Ürün Başlığı (EN)",
      adminVolume: "Hacim (Örn: 550 CC)",
      adminImage: "Görsel URL",
      adminSave: "Kaydet & Yayınla",
      adminCancel: "Kapat",
      adminResetData: "Varsayılana Sıfırla"
    },
    en: {
      brand: "KRAFTEN PACKAGING",
      tagline: "Innovative Packaging, Eco-Friendly Future",
      navHome: "HOME",
      navVision: "VISION",
      navProducts: "INDUSTRIAL SOLUTIONS",
      navCertificates: "CERTIFICATES",
      navBlog: "BLOG",
      navSustainability: "SUSTAINABILITY",
      navContactBtn: "CONTACT US",
      heroSubtitle: "GLOBAL PACKAGING INDUSTRY",
      heroTitle: "Redefining<br>Excellence.",
      heroDesc: "Innovative packaging solutions inspired by nature, meeting international food safety standards.",
      heroBtn: "Discover Solutions",
      visionHeading: "Shaping the Future",
      visionBody: "At Kraften Packaging, we don't just produce packaging; we rebuild the industrial ecosystem with eco-friendly and 99% recyclable raw materials. Quality, hygiene, and prestige are in our DNA.",
      statEco: "Recyclable",
      statIso: "22000 Standards",
      statFsc: "Certified Production",
      statExport: "Export to 30+ Countries",
      btnCatalog: "E-Catalog (PDF)",
      btnSample: "Request Free Sample",
      sampleModalTitle: "Corporate Free Sample Request",
      sampleModalDesc: "We will ship our food-contact certified paper container samples directly to your business address.",
      sampleCompany: "Company Name *",
      sampleName: "Contact Full Name *",
      samplePhone: "Phone / WhatsApp *",
      sampleProduct: "Product Group of Interest",
      sampleAddress: "Delivery Address *",
      btnSubmitSample: "Submit Sample Request",
      waWidgetText: "Quick Quote & WhatsApp",
      prodSub: "PREMIUM FOOD CONTAINERS",
      prodHeading: "Industrial Product Line",
      allCategories: "All Categories",
      searchPlaceholder: "Search product (e.g., Kraft, 550 CC)...",
      specTitle: "Technical Specifications",
      topDiameter: "Top Diameter",
      bottomDiameter: "Bottom Diameter",
      height: "Height",
      volume: "Volume",
      boxQty: "Box Quantity",
      boxDimensions: "Box Dimensions",
      btnWhatsappQuote: "Order & Quote via WhatsApp",
      certTitle: "International Accreditation",
      certSub: "All our distributed food packaging products are FSC and food-contact certified.",
      blogTitle: "Sectoral News & Articles",
      blogViewAll: "View All Articles →",
      blogHeroSubtitle: "KRAFTEN INSIGHTS & NEWS",
      blogHeroTitle: "Latest Insights from<br>Packaging World",
      blogSearchPlaceholder: "Search news or article...",
      blogBackToHome: "← Back to Home",
      readMore: "Read More →",
      susTitle: "Zero Carbon Footprint Goal.",
      susDesc: "We are committed to protecting nature at every step from our production lines to the end consumer. We lead the sector with innovative R&D investments.",
      susBtn: "Sustainability Report",
      footerDesc: "Innovative and sustainable packaging solutions.",
      adminTitle: "Kraften - Executive Admin Panel",
      adminAddCategory: "Add New Category",
      adminAddProduct: "Add New Product",
      adminCategoryNameTr: "Category Name (TR)",
      adminCategoryNameEn: "Category Name (EN)",
      adminProductTitleTr: "Product Title (TR)",
      adminProductTitleEn: "Product Title (EN)",
      adminVolume: "Volume (e.g., 550 CC)",
      adminImage: "Image URL",
      adminSave: "Save & Publish",
      adminCancel: "Close",
      adminResetData: "Reset to Default"
    }
  };
